// ==UserScript==
// @name         eVK
// @namespace    https://github.com/ElFlayder/eVK
// @version      0.3
// @description  Редизайн ВК от ElFlayder
// @author       ElFlayder
// @include      http://vk.com/*
// @include      https://vk.com/*
// @include      http://*.vk.com/*
// @include      https://*.vk.com/*
// @run-at       document-start
// ==/UserScript==

window.onload = (function() {var css = [
    "#page_header_cont .back {",
    "    background-color: #f9f9f9;",
    "    border-bottom: 1px solid #f9f9f9;",
    "}",
    "",
    ".left_menu_nav_wrap {",
    "    display: none;",
    "    overflow: hidden;",
    "    visibility: hidden;",
    "}",
    "",
    ".left_menu_nav {",
    "    display: none;",
    "    overflow: hidden;",
    "    visibility: hidden;",
    "}",
    "",
    "#ads_left {",
    "    display: none;",
    "    overflow: hidden;",
    "    visibility: hidden;",
    "}",
    "",
    "#page_header_wrap {",
    "    width: 100% !important;",
    "}",
    "",
    ".top_home_link .top_home_logo {",
    "    background: url(https://psv4.userapi.com/c856432/u538916773/docs/d18/cdc744d2fe61/VK_Logo.png?extra=aO9QqWu1kR2GLbuwv60qE2FxuPJd3EN1JHplmUyi8jhJ-MKue0daGpIBLMRmxGFULGtUnoKyZNqlMT8bVP0kX72I3rCXBVTRhelldPofTytHSAnUGbD1Oa_wU4j2wzSeWcveOGD9OgeCXENaKifZCcbtPA) no-repeat 50% / contain;",
    "    width: 46px;",
    "    height: 36px;",
    "    margin: 3px 10px 0 0;",
    "}",
    "",
	"input.text.ts_input {",
	"    width: 240px;",
	"    border-radius: 7px;",
	"    background: #ecedf1;",
	"}",
	"",
    ".top_nav_btn {",
    "    width: 46px;",
    "    height: 42px;",
    "}",
    "",
    ".top_nav_btn .top_nav_btn_icon {",
    "    margin: 7px auto;",
    "}",
    "",
    ".top_nav_btn#top_notify_btn .top_nav_btn_icon {",
    "    background-image: url(https://m.vk.com//images/mobile/icons/sprites/menu-7a14d06d.svg)!important;",
    "    background-position-y: -44px;",
    "    background-position-x: -158px;",
    "    background-size: 184px 248px;",
    "    width: 27px!important;",
    "    height: 27px!important;",
    "}",
    "",
    ".top_nav_btn.active {",
    "   background-color: #ecedf1;",
    "}",
    "",
    ".top_nav_btn:hover {",
    "   background-color: #ecedf1;",
    "}",
    "",
    ".top_audio_player .top_audio_player_btn .top_audio_player_btn_icon {",
    "   filter: invert(1);",
    "}",
    "",
	".top_audio_player .top_audio_player_title {",
	"    color: #5f5f5f;",
	"}",
	"",
    ".top_audio_player:hover {",
    "   background-color: #ecedf1;",
    "}",
    "",
    "#top_notify_wrap {",
    "   background-color: #f9f9f9;",
    "   border-bottom: 1px solid #f9f9f9;",
    "   box-shadow: 0 0 64px rgba(0,0,0,.24), 0 0 0 1px rgba(0,0,0,.08);",
    "}",
    "",
    "#page_header {",
    "   width: 100% !important;",
    "   padding: 0;",
    "}",
    "",
    ".top_nav_link {",
    "   color: #5f5f5f;",
    "   font-weight: 400;",
    "}",
    "",
    ".top_nav_link:hover {",
    "   background-color: #ecedf1;",
    "}",
    "",
    ".top_nav_link.active {",
    "   background-color: #ecedf1;",
    "}",
    "",
    ".top_profile_arrow {",
    "   filter: invert(1);",
    "}",
    "",
    ".top_notify_count {",
    "  background-color: #ff3347;",
    "  border: 1px solid #ff3347;",
    "}",
    "",
    "#top_profile_menu {",
    "  background: #ffffff;",
    "  border-radius: 6px;",
    "  box-shadow: 0 0 64px rgba(0,0,0,.24), 0 0 0 1px rgba(0,0,0,.08);",
    "  border: 1px solid #e1e3e6;",
    "}",
    "",
    "#audio_layer_tt {",
    "  border-radius: 0 0 6px 6px;",
    "  box-shadow: none;",
    "  border: 1px solid #e1e3e6;",
    "  border-top: none;",
    "}",
    "",
    ".audio_page_player2 .audio_page_player_next, .audio_page_player2 .audio_page_player_prev {",
    "  filter: grayscale(1);",
    "}",
    "",
    ".audio_page_player2 .audio_page_player_play .icon {",
    "  background-color: #999999;",
    "}",
    "",
    ".audio_page_player2:hover .audio_page_player_play:hover .icon:hover {",
    "  background-color: #707070;",
    "}",
    "",//левая панель

	"#side_bar #l_skpg a ",
	"{",
	"    padding-left: 8px !important",
	"}",
	"",
	"#side_bar:hover .left_menu_nav_wrap ",
	"{",
	"    opacity: 0.5 !important",
	"}",
	"",
	"#side_bar:hover .left_menu_nav_wrap:hover ",
	"{",
	"    opacity: 1 !important",
	"}",
	"",
	"#side_bar #l_skpg a .left_label ",
	"{",
	"    width: 137px !important",
	"",
	"}",
	"",
	"#side_bar {background: rgb(249, 249, 249) !important; position: fixed !important; top: 0 !important; padding-top: 45px !important; bottom: 0 !important; left: 0 !important; width: 48px !important; z-index: 119 !important; overflow: hidden !important; transition: 0.5s !important}",
	"",
	".side_bar_inner {background: rgb(249, 249, 249) !important; position: fixed !important; top: 0 !important; padding-top: 45px !important; bottom: 0 !important; left: 0 !important; width: 48px !important; height: auto !important; z-index: 119 !important; overflow: hidden !important; transition: 0.5s !important}",
	"",
	"  #side_bar:hover {overflow-x: hidden !important; overflow-y: auto !important; transition: 0.5s !important}",
	"",
	"  .side_bar_inner:hover {overflow-x: hidden !important; overflow-y: auto !important; width: 268px !important; transition: 0.5s !important}",
	"  ",
	"  #side_bar_inner ol {padding: 0 !important}",
	"  #side_bar li {background: none !important; padding: 3px 16px 3px 8px !important; margin: 0 !important; width: 244px !important}",
	"  #side_bar .left_label {padding-left: 12px !important}",
	"  #side_bar_inner #l_pr {padding-top: 4px !important}",
	"  ",
    "  #side_bar #l_pr .left_icon {background-position: -112px -136px;}",
    "  #side_bar #l_nwsf .left_icon {background-position: -103px -163px;}",
    "  #side_bar #l_msg .left_icon {background-position: -83px -108px;}",
    "  #side_bar #l_fr .left_icon {background-position: 3px -164px;}",
    "  #side_bar #l_ph .left_icon {background-position: -26px -50px;}",
    "  #side_bar #l_aud .left_icon {background-position: -27px -137px;}",
    "  #side_bar #l_vid .left_icon {background-position: -27px -166px;}",
    "  #side_bar #l_vkp .left_icon {background-position: -83px -51px;}",
    "  #side_bar #l_mk .left_icon {background-position: -55px -137px;}",
    "  #side_bar #l_fav .left_icon {background-position: -56px -50px;}",
    "  #side_bar #l_doc .left_icon {background-position: -28px -80px;}",
    "  #side_bar #l_bt .left_icon {background-position: 2px -51px;}",
    "  #side_bar #l_ap .left_icon, #side_bar #l_apm .left_icon {background-position: -54px -79px;}",
    "  #side_bar #l_gr .left_icon, #side_bar .l_comm .left_icon {background-position: 3px -164px;}",
	"  #side_bar .left_icon {margin-top: -2px !important; opacity: 1 !important; background-position-x: -136px; background-position-y: -112px; background-size: 167px 248px; width: 30px !important; background-image: url(https://m.vk.com//images/mobile/icons/sprites/menu-7a14d06d.svg) !important;}",
	"  #side_bar #l_skpg .left_label {padding-left: 34px !important; background: url(https://i.ibb.co/ZV0Ch3r/menu-icon-whitetransp.png) 0 -526px no-repeat !important}",
	"  #side_bar ol li .left_row .left_count_wrap {width: 48px !important; height: 26px !important; padding: 2px 0 0 0 !important; margin: 0 0 0 -8px !important; text-align: center !important}",
	"  ",
	".left_count_wrap {",
	"    color: #3f9fd2;",
	"    background: #00000000;",
	"}",
	"",
	"  #side_bar ol li .left_row .left_count_wrap:hover {",
	"    color: #3f9fd2;",
	"    background: #00000000;",
	"}",
	"",
	"#side_bar li {",
	"",
	"    width: 160px !important;",
	"}",
	"",
	".top_notify_header {",
	"    background: #f9f9f9;",
	"}",
	"",
	"#top_notify_wrap {",
	"    box-shadow: none;",
	"}",
	"",
	".side_bar_inner:hover {",
	"",
	"    width: 180px !important;",
	"}",
	"",
	"#side_bar ol li .left_row .left_count_wrap {",
	"    width: 47px !important;",
	"    position: absolute;",
	"    height: 27px !important;",
	"    padding: 0px 0px 0px 11px !important;",
	"}",
    "",
    ".button_gray button, .flat_button.secondary {",
    "   background-color: #f2f3f5;",
    "   color: #4986cc;",
    "   font-weight: 500;",
    "   border-radius: 10px;",
    "}",
    "",
    ".top_nav_btn#top_audio .top_nav_btn_icon {",
    "    background-image: url(https://m.vk.com//images/mobile/icons/sprites/menu-7a14d06d.svg)!important;",
    "    background-position-y: -142px;",
    "    background-position-x: -36px;",
    "    background-size: 184px 248px;",
	"    width: 27px!important;",
	"    height: 27px!important;",
    "}",
    "",
    ".top_audio_play__button {",
    "    background-color: #ecedf1;",
    "}",
    "",
    ".top_audio_play__button:before {",
    "    background-color: #ecedf1;",
    "}",
    "",
    ".top_audio_play__button:hover {",
    "    background-color: #e4e5e8;",
    "}",
    "",
    ".top_audio_play__button:hover:before {",
    "    background-color: #e4e5e8;",
    "}",
    "",
    ".button_blue button, .button_gray button, .button_light_gray button, .flat_button {",
    "   border-radius: 10px; !important",
    "   font-weight: 500; !important",
    "}",
    "",
    ".profile_msg_split .profile_btn_cut_left {",
    "   border-radius: 10px 0 0 10px;",
    "   font-weight: 500;",
    "}",
    "",
    ".profile_msg_split .profile_btn_cut_right {",
    "   border-radius: 0 10px 10px 0;",
    "   font-weight: 500;",
    "}",
    "",
    ".im-page--dialogs-search.ui_search_custom .ui_search_field {",
    "   height: 35px;",
    "   background-color: #ebedf0;",
    "   padding: 0 20px;",
    "   margin: 8px;",
    "   border-radius: 10px;",
    "}",
    "",
    ".side_bar_inner {margin-top: 5px;}",
    "",
    ".ui_rmenu_item_sel, .ui_rmenu_item_sel:hover {",
    "   border-left: 2px solid #575757;",
    "}",
    "",
    ".ui_rmenu_item_sel {background-color: #eaeaea; }",
    "",
    ".top_home_link { padding: 3px; }",
    "",
    "#side_bar .more_div { display: none; }",
    "",
    "#stl_bg { margin-left: 20px; }",
    "",
    ".chat_onl_wrap { display: none !important; }",
    "",
    "::-webkit-scrollbar-track { background-color: #f9f9f9; }",
    "",
    "::-webkit-scrollbar { width: 6px; background-color: #42a5f5; }",
    "",
    "::-webkit-scrollbar-thumb { background-color: #42a5f5; border-radius: 5px; }",
    "",
    ".left_count_wrap .inl_bl { padding: 1px 4px; border-radius: 12px; color: #fff; font-size: 9px; height: 11px; line-height: 11px; min-width: 5px; top: 3px; left: 25px; background-color: #ff3347; text-align: center; position: absolute; z-index: 1; }",
    "",
    "#content { margin-left: -10vw; }",
    ""
].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
document.getElementById("l_pr").innerHTML = "";
});
